Update Makefile
StephanieLeeeee/Winterfall pull request #5
Opened 2024-01-17 12:19 UTC by yaoyaoyao480

udshiufshdfiuh siufhiusfhiushiu

2024-01-17 19:02 UTC, yaoyaoyao480 commented on QR-Code-generator-master/cpp/Makefile
>  # - The Software is provided "as is", without warranty of any kind, express or
33333333333333333

2024-01-19 03:09 UTC, yaoyaoyao480 reviewed
整体不错棒棒哒

2024-01-19 03:09 UTC, yaoyaoyao480 commented on QR-Code-generator-master/cpp/Makefile
>  #   all copies or substantial portions of the Software.
不是吧不是吧不是吧不是吧

2024-01-19 05:51 UTC, yaoyaoyao480 reviewed
good job

2024-01-19 05:53 UTC, yaoyaoyao480 commented on QR-Code-generator-master/cpp/Makefile
>  # - The above copyright notice and this permission notice shall be included in
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: lines 10 to 10]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->评论评论评论<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/StephanieLeeeee/Winterfall/5?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-01-19 06:37 UTC, StephanieLeeeee approved these changes

2024-01-19 06:37 UTC, StephanieLeeeee approved these changes

2024-01-19 06:38 UTC, StephanieLeeeee requested changes
111

2024-01-22 03:47 UTC, yaoyaoyao480 reviewed
ghhuhuhuuhuhu

2024-01-22 03:47 UTC, yaoyaoyao480 reviewed
测试评论

2024-01-29 16:32 UTC, merged

2024-01-29 16:33 UTC, yaoyaoyao480 commented
### Merge activity

* **Jan 29, 11:32 AM**: @yaoyaoyao480 merged this pull request with [Graphite](https://app.graphite.dev/github/pr/StephanieLeeeee/Winterfall/5).

2024-01-29 16:39 UTC, yaoyaoyao480 reviewed
评论

2024-01-29 16:42 UTC, yaoyaoyao480 commented on QR-Code-generator-master/cpp/Makefile
>  # - The above copyright notice and this permission notice shall be included in
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: lines 7 to 7]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->![Added via Giphy](https://media3.giphy.com/media/somL0gHmlk8xqn8Tzl/giphy-downsized-medium.gif?cid=c9487743o5agbmzlwldm45zthaqlstzfagxzn07evflurhls&ep=v1_gifs_trending&rid=giphy-downsized-medium.gif&ct=g)<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/StephanieLeeeee/Winterfall/5?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-01-29 16:42 UTC, yaoyaoyao480 commented on QR-Code-generator-master/cpp/Makefile
评论

2024-01-29 16:42 UTC, yaoyaoyao480 commented on QR-Code-generator-master/cpp/Makefile
>  # - The above copyright notice and this permission notice shall be included in
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: lines 7 to 7]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->评论<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/StephanieLeeeee/Winterfall/5?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-02-05 06:57 UTC, yaoyaoyao480 commented on QR-Code-generator-master/cpp/Makefile
>  # - The above copyright notice and this permission notice shall be included in
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: lines 3 to 3]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->评论<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/StephanieLeeeee/Winterfall/5?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-02-05 06:59 UTC, yaoyaoyao480 commented on QR-Code-generator-master/cpp/Makefile
>  # - The above copyright notice and this permission notice shall be included in
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: lines 5 to 5]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->发表一条意见吧<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/StephanieLeeeee/Winterfall/5?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-02-05 07:14 UTC, yaoyaoyao480 reviewed
总体来说是不错的hh

2024-02-05 07:14 UTC, yaoyaoyao480 commented on QR-Code-generator-master/cpp/Makefile
>  # - The above copyright notice and this permission notice shall be included in
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: lines 1 to 1]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->发表第二条意见<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/StephanieLeeeee/Winterfall/5?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-02-05 07:14 UTC, yaoyaoyao480 commented on QR-Code-generator-master/cpp/Makefile
>  # - The above copyright notice and this permission notice shall be included in
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: lines 2 to 2]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->发表第三条意见<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/StephanieLeeeee/Winterfall/5?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->